config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get "/login" => "user_sessions#new", as: :login
  delete "logout" => "user_sessions#destroy", as: :logout
  
  resources :users, except: [:show]
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    put :email, on: :member
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'pages#home'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :todo_lists
  
  validates :email, presence: true, 
                    uniqueness: true,
                    format: {
                      with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/
                    }
  before_save :downcase_email
  
  def downcase_email
    self.email = email.downcase
  end
  
  def generate_password_reset_token!
    update_attribute(:password_reset_token, SecureRandom.urlsafe_base64(48))
  end
  
  def create_default_lists
    tutorial = todo_lists.find_or_create_by(title: "ODOT Tutorial")
    tutorial.todo_items.find_or_create_by(content: "Add a todo list or item by clicking the \"+\" button at the top.")
    tutorial.todo_items.find_or_create_by(content: "The numbers next to a list indicate how many items it has.")
    tutorial.todo_items.find_or_create_by(content: "Clicking or tapping the list title brings up list items.")
    tutorial.todo_items.find_or_create_by(content: "Clicking or tapping the list title again gives you more options.")
    tutorial.todo_items.find_or_create_by(content: "Clicking or tapping a checkmark next to an item marks it complete.")
    tutorial.todo_items.find_or_create_by(content: "Clicking or tapping it again marks it incomplete.")
    tutorial.todo_items.find_or_create_by(content: "Clicking or tapping the item lets you edit or delete it.")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.create_default_lists
        session[:user_id] = @user.id
        format.html { redirect_to todo_lists_path, notice: 'User was successfully created.', success: "Thanks for signing up!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to todo_lists_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "First Name" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, "Last Name" %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password (again)" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= title "Account Settings" %>

<%= form_for(@user, builder: FoundationFormBuilder) do |f| %>
  
  <fieldset>
    <legend>About You</legend>
    <%= f.text_field :first_name, autofocus: 'autofocus' %>
    <%= f.text_field :last_name %>
    <%= f.email_field :email %>
  </fieldset>
  
  <fieldset>
    <legend>Change Your Password</legend>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
  </fieldset>
  
    <%= f.submit "Save", class: "button radius expand" %>
<% end %>

app/views/users/new.html.erb
<%= title "Register for ODOT" %>

<%= form_for(@user, builder: FoundationFormBuilder) do |f| %>
    <%= f.text_field :first_name, autofocus: 'autofocus' %>
    <%= f.text_field :last_name %>
    <%= f.email_field :email %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    
    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>