config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get "/login" => "user_sessions#new", as: :login
  delete "logout" => "user_sessions#destroy", as: :logout
  
  resources :users, except: [:show]
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    put :email, on: :member
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'pages#home'
  
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-alert class="flash alert-box text-center <%= type %>">
    <%= message %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_header_logged_in.html.erb
<div class="small-4 columns header-icon">
  <% if @go_back_link_to%>
    <%= link_to "Back", @go_back_link_to, class: "icon-arrow-left hide-text" %>
  <% else %>
    <%= link_to "Sign Out", logout_path, method: :delete, class: "icon-signout hide-text" %>
  <% end %>
</div>
<div class="small-4 columns">
  <h1 class="logo"><%= link_to "Odot", todo_lists_path, class: "hide-text" %></h1>
</div>
<div class="small-4 columns header-icon">
  <%= new_item_link %>
</div>

app/views/layouts/_header_logged_out.html.erb
<div class="small-12 columns">
  <h1 class="logo"><%= link_to "Odot", root_path, class: "hide-text" %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %>Odot</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |type, message| %>
    <div class="flash alert-box text-center <%= type %>">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

  <header class="row global-header">
    <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns">
      <% if logged_in? %>
        <%= render partial: 'layouts/header_logged_in' %>
      <% else %>
        <%= render partial: 'layouts/header_logged_out' %>
      <% end %>
    </div>
  </header>

  <div class="row collapse">
    <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns">
      <%= yield %>
    </div>
  </div>

  <footer class="row global-footer">
    <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns text-center">
      <% if logged_in? %>
        <%= link_to "Settings", edit_user_path(current_user) %>
      <% end %>
    </div>
  </footer>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body class="home">
  <%= render partial: "layouts/flash" %>
  <header class="row global-header">
    <div class="small-12 small-centered columns">
      <%= render partial: 'layouts/header_logged_out' %>
    </div>
  </header>
  
  <%= yield %>

  <footer class="row global-footer">
    <div class="small-12 small-centered columns text-center">
      <%= link_to "Already have an account? Sign in.", login_path %>
    </div>
  </footer>
  
</body>
</html>